uafrica/ui-framework

src/Dropdown.tsx, src/Input.tsx, src/Textarea.tsx, src/datePicker/DatePicker.tsx, src/datePicker/DatePickerContext.ts, src/index.scss
Time select on date picker and other small changes
=> Time select on date picker

src/InfoButton.tsx
- The info button popup did not display correctly when used on table headings
- The info button would open the popup partially off screen in some cases
=> updated info button to work with popper and a portal

Demo/src/App.tsx, Demo/src/components/Modals.tsx, src/Modal.tsx, src/SavePanel.tsx, src/Select.tsx, src/datePicker/DatePicker.tsx, src/index.scss
- bigger z-index for some popups to stop overlapping incorrectly with other elements
- changed modals to work with portals. allows nested modals to work better
- updated demo with nested modals
- changed save panel to show error message next to save button
=> various improvements

src/Select.tsx
Select dropdowns on the edge of the screen would fall off the screen in some places. Popper moves the dropdown to an acceptable position on-screen
=> updated select dropdown to open using popper

src/Accordion.tsx
Allow developer to indicate if no caret should be in the accordion header.
=> Added option to exclude caret from Accordion.tsx

Demo/src/components/Modals.tsx, src/hooks/usePrevious.ts, src/hooks/useTabs.ts
useTabs hook to use with Tabs on pages.
=> Added hooks for usePrevious and useTabs

src/hooks/usePrevious.ts, src/hooks/useTabs.ts
=> Added hooks for usePrevious and useTabs exports

src/Input.tsx, src/hooks/useTabs.ts
Give the developer the ability to specify the prepend text size in an input.
=> Add option to select prepend text size

Demo/src/components/Tables.tsx, Demo/src/components/Tabs.tsx, src/Table.tsx
Passing a `tableHeadColor` prop to the <Table.Head> tag
=> Expanded table head to select a color for the background

Demo/src/components/Forms.tsx, src/Textarea.tsx
Change background colour of disabled textarea
=> Add styles for disabled textarea

.gitignore, Demo/src/components/Modals.tsx, src/Accordion.tsx
Set caret color if included, else set to primary color
=> Accordion caret color

Demo/src/components/Forms.tsx, src/Button.tsx, src/Dropdown.tsx
Can decide border colour for dropdown. Added rounded left and rounded right props to button
=> Add dropdown color, button left and right rounded optional props

Demo/src/components/Forms.tsx, src/Dropdown.tsx
Added square property to dropdown
=> Add square option to dropdown

Demo/tailwind.config.js, src/Dropdown.tsx, src/Input.tsx, src/Textarea.tsx
Truncate dropdown menu title if necessary. Moved applied styles of Input and Textarea fields to components.
=> Truncate dropdown title and input focus colour

.idea/prettier.xml, Demo/src/components/Buttons.tsx, Demo/src/components/Tabs.tsx, src/Button.tsx, src/Dropdown.tsx, src/Message.tsx
Added dropdown offset to match select offset.
Include an optional close prop to the message that will allow the user to close the message.
=> Dropdown offset and close option for message bar

Demo/src/components/Forms.tsx, src/Checkbox.tsx
Set checkbox colour to custom prop and by default primary
=> Add prop to set custom checkbox color

Demo/src/components/Modals.tsx, src/Accordion.tsx, src/hooks/useOnClickOutside.ts
Added an on click outside hook to the framework content option to accordion endContent
=> Accordion and add on click outside

Demo/src/components/FailComponent.tsx, Demo/src/components/Modals.tsx, package.json, src/ErrorBoundary/ErrorState.tsx, src/ErrorBoundary/withError.tsx, src/hooks/useOnClickOutside.ts, src/index.tsx, yarn.lock
Include error boundaries on exported components
=> Added withError HOC

package.json, src/customTable/CustomTable.tsx, src/utils/generalUtils.tsx
Added effects to run when the column order or width changes. This allows the developer to only set the column width after the component mounts when using the custom table component.
=> Added prop effects to change column width and order on prop changes

src/customTable/CustomTable.tsx
Allow the developer to pass an icon prop to specify the icon of the draggable row icon
Return the starting and ending index of the dragged row in the `onRowOrderChanged` function
=> Expanding custom table

docs/hooks.md, package.json, src/InfoPopover.tsx, src/hooks/useDebounce.ts, src/hooks/useFilters.ts, src/hooks/useLocationState.ts, src/index.tsx, src/utils/generalUtils.tsx
Added various filters as well as documentation for the filters
=> Added custom hooks for debounce, location state and filters (also added docs)

src/InfoButton.tsx
Add `icon` prop to `InfoButton` component so that we can change the icon of the info button.
=> Add `icon` prop to `InfoButton` component
